### ISSUE TITLE
React.createClass versus extends React.Component and expressing components as pure functions

### ISSUE THREAD

**Issue by StanLindsey** [tomRedox/simpleCRM#24]
We're currently using React.createClass, the v1.3 guide uses React.Component ES6 syntax (http://guide.meteor.com/v1.3/react.html).

This seems to explain the differences it very well: https://toddmotto.com/react-create-class-versus-component/ 
Ending with:

> Facebook does suggest the future removal of React.createClass completely in favour of ES6 classes. For now, use what makes sense, they’re both just syntax with different semantics that do the same thing - they’re both classes!

Discuss!

**Comment by tomRedox** [comment]
I'm definitely for ES6 and I should practice what I preach.. http://stackoverflow.com/questions/35058241/which-reactjs-syntax-to-use-react-createclass-or-es6-extends/35058496#35058496 :laughing:  The 1.3 docs on React didn't exist (or I hadn't read them) when I wrote the classes so I went wit the mixin.

There seems to be a bit of a battle going on between ReactTracker, ReactKomposer and the MDG React integration, I was waiting to see which way that went before switching it all over.

Edit:   However, that's probably a non-issue now with Redux as the mixin isn't in every class like it used to be.

**Comment by StanLindsey** [comment]
That seems like a good reason to wait, we don't want to have to refactor this multiple times.

**Comment by tomRedox** [comment]
The other thing we need to consider here is whether to express dumb components as pure functions instead of classes, which I believe is favoured by some parts of the community, although I'm not sure why - possibly it simplifies testing?  https://facebook.github.io/react/docs/reusable-components.html#stateless-functions.
