### ISSUE TITLE
your server is down 

### ISSUE THREAD

**Issue by daslicht** [tomRedox/simpleCRM#29]
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 5203465 bytes) in /home/linweb38/r/redox-software.co.uk/user/htdocs/libraries/joomla/cache/storage/file.php on line 129

**Comment by tomRedox** [comment]
Thank you.  I've flushed the cache, hopefully that's sorted it.  I really need to get our site switched off Joomla.

**Comment by daslicht** [comment]
yeah !
